load("@rules_scala//scala:scala.bzl", "scala_binary", "scala_library")

scala_binary(
    name = "main",
    srcs = ["Main.scala"],
    main_class = "com.example.Main",
    deps = [
        "@maven//:com_lihaoyi_os_lib_3_0_11_9_M7"
    ]
)
